name: helloGithubAction
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     # run 뒤에는 실제 작동하는 코드를 넣어야 합니다.
    #- name: hello world 출력!!
     # run: echo Hello, world!
    - name: 디렉토리 출력!!
      run: ls -al
   # - name: 1. 파이썬 버전 출력!!
    #  run: python -V
    - uses: actions/checkout@v2     
    - name: 2. 파이썬 패키지 확인!!
      run: pip list
    - name: 3. 파이썬 업그레이드 
      run: python -m pip install -- upgrade pip
    - name: 3. 파이썬패키지 install
      run: pip install -r reqirements.txt
    - name: 4. 파이썬 실행!!
      run: python test.py

    #- name: 파이썬 파일찾기!!
     # run: find / - name 'test.py'
 
